.\" Manpage for bug-gscpp.
.\" Contact billsix@gmail.com to correct errors or typos.
.TH man 1 "19 May 2015" "0.0.1" "bug-gscpp man page"
.SH NAME
bug-gscpp \- Bill's Utilities for Gambit - scheme preprocessor
.SH SYNOPSIS
bug-gscpp [input-file output-file]
.SH DESCRIPTION
bug-gscpp is a preprocessor for Gambit C Scheme.  It turns "[foo...]" into "(lambda () foo...)" and "[|args...|foo...]" into "(lambda (args...) foo...)"
.SH OPTIONS
With no arguments, uses standard in and standard out.  If two arguments are provided, bug-gscpp reads input-file and outputs to output-file
.SH SEE ALSO
gsi(1),bug-gsi(1),
.SH BUGS
No known bugs.
.SH AUTHOR
William Emerison Six (billsix@gmail.com)